basic tests for create_prop_scr
GSK-Biostatistics/beastt pull request #2
Opened 2023-12-07 17:45 UTC by statasaurus

2023-12-08 08:50 UTC, statasaurus commented on tests/testthat/test-create_prop_scr.R
> +  expect_error(create_prop_scr(internal_df, as.tibble(internal_df), id_col, model))
see previous comment about as.tibble

2023-12-08 08:50 UTC, statasaurus commented on tests/testthat/test-create_prop_scr.R
> +  expect_error(create_prop_scr(internal_df, external_df, id_col, "cov1+cov2"))
This is a duplicate test given the function doesn't accept any strings in this parameter

2023-12-08 19:21 UTC, bcarancibia commented
This is initial tests, we had talked about writing tests with the paper that Nate is able to provide to recreate results. Is the plan to do a second PR with tests?

2023-12-08 19:24 UTC, bcarancibia requested changes
Changes to be implemented before merging. Please close out comment / feedback.

2023-12-11 11:44 UTC, ShmoopyE commented on tests/testthat/test-create_prop_scr.R
> +  expect_error(create_prop_scr(as.tibble(internal_df), external_df, id_col, model))
I wrote this test assuming that only data.frame would be required as an input for both internal and external data (same for the matrix test). Happy to update the tests if we want tibbles and matrices as valid inputs and update the code to do so, otherwise if only data.frame is required I can leave the tests as they are now and maybe we can make this clear in the function arguments.

2023-12-11 12:02 UTC, ShmoopyE commented
> This is initial tests, we had talked about writing tests with the paper that Nate is able to provide to recreate results. Is the plan to do a second PR with tests?

Will update the current PR, thanks

2024-01-25 14:25 UTC, bcarancibia commented
closing this based on updated code in new PR

2024-01-25 14:25 UTC, closed without merging