Resolve issue #55
GSK-Biostatistics/beastt pull request #57
Opened 2024-10-16 15:17 UTC by abiterry

2024-10-17 09:05 UTC, statasaurus requested changes
Looks good. I just have a few suggestions. Also, now that I am thinking about it. It is probably better if we make the binary analysis options a module cause then we can reuse it across the simulation and analysis case

2024-10-17 09:05 UTC, statasaurus commented on R/app.R
> +                    "Robustify Power Prior")
```suggestion
     
```

2024-10-17 09:05 UTC, statasaurus commented on R/app.R
> +                                      "Other")),
```suggestion

```

2024-10-28 10:46 UTC, abiterry commented on R/mod_plot.R
> +                                         c("Historgram", "Historgram - IPW",
Histogram spelling

2024-10-28 11:53 UTC, statasaurus approved these changes

2024-10-28 11:53 UTC, statasaurus commented on R/mod_plot.R
> +                                         c("Historgram", "Historgram - IPW",
```suggestion
                                         c("Histogram", "Histogram - IPW",
```

2024-10-28 11:53 UTC, merged